# Generated by Django 3.2.4 on 2021-07-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=3000)),
                ('name', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='posts/')),
                ('personaljob', models.TextField(max_length=100)),
            ],
        ),
    ]
